### ISSUE TITLE
Nuxt gives error

### ISSUE THREAD

**Issue by Venegrad** [nuxt-community/style-resources-module#128]
![image](https://user-images.githubusercontent.com/9676703/97988376-8de14880-1de5-11eb-856c-abbd03d69123.png)

```
odule build failed (from ./node_modules/stylus-loader/dist/cjs.js):                                                                                                                    friendly-errors 15:01:16
ValidationError: Invalid options object. Stylus Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'import'. These properties are valid:
   object { stylusOptions?, sourceMap?, webpackImporter?, additionalData? }
    at validate (C:\Users\veneg\Desktop\qonversation\node_modules\stylus-loader\node_modules\schema-utils\dist\validate.js:104:11)
    at Object.stylusLoader (C:\Users\veneg\Desktop\qonversation\node_modules\stylus-loader\dist\index.js:24:29)
                                                                                                                                                                                        friendly-errors 15:01:16  
 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/stylus-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./components/frames/page-aside.vue?vue&type=style&index=0&lang=stylus& 4:14-452 14:3-18:5 15:22-460
 @ ./components/frames/page-aside.vue?vue&type=style&index=0&lang=stylus&
 @ ./components/frames/page-aside.vue
 @ ./layouts/default.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

**Comment by Venegrad** [comment]
![image](https://user-images.githubusercontent.com/9676703/97988406-98034700-1de5-11eb-8908-6b66c7a0bf95.png)

**Comment by galaczi** [comment]
https://github.com/vuejs/vue-cli/issues/5947

Downgrading solved it for me.
