### ISSUE TITLE
FATAL  Nuxt Build Error

### ISSUE THREAD

**Issue by chiboreache** [nuxt-community/style-resources-module#37]
Wildcard import — causing error
Dot import — simple not working

```coffeescript
  # Nuxt.js modules
  modules:
    [
      '@nuxtjs/style-resources'
      './modules/coffeescript'
    ]

  styleResources:
    stylus:
      [
        '~assets/*.styl' 
         or './assets/*.styl'

        '~assets/mixins.styl'
        '~assets/card-base.styl'
      ]
```

npx nuxt build →
*Version: webpack 4.29.6*

```js

ERROR in ./components/GHCard.vue?vue&type=style&index=0&id=0e928d29&lang=stylus&scoped=true& (./node_modules/css-loader/dist/cjs.js??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--10-oneOf-1-2!./node_modules/stylus-loader??ref--10-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./components/GHCard.vue?vue&type=style&index=0&id=0e928d29&lang=stylus&scoped=true&)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'type' of undefined

```

and so on

```json

"dependencies": {
    "@nuxtjs/style-resources": "^0.1.2",
    "axios": "^0.18.0",
    "coffee-loader": "^0.8.0",
    "coffeescript": "^2.0.1",
    "nuxt": "*",
    "pug": "^2.0.3",
    "pug-plain-loader": "^1.0.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2"
  }

```

**Comment by chiboreache** [comment]
I also tried  [nuxt-stylus-resources-loader](https://github.com/BKWLD/nuxt-stylus-resources-loader)

```js
resolve = require('path').resolve
['nuxt-stylus-resources-loader', resolve(__dirname, 'assets/**/*.styl')]
```

with almost the same result, error message now is a little bit more verbose

```js
at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5262:15)
at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by manniL** [comment]
@chiboreache Hey :wave: 

Please provide a reproduction repo.

Dynamic asset imports should work like shown in 
https://github.com/nuxt-community/style-resources-module/blob/master/test/fixture/sass/nuxt.config.js#L11 
(pre-processor-independent)

**Comment by chiboreache** [comment]
@manniL hello again :hand: 

Nice link, but I'm using **stylus** ;)

so example file says

```js
styleResources: {
    stylus: ['~assets/variables.styl']
  },
```

I can't provide anything, I just have mixins and styl file with classes, which are I want to reuse by importing in pages via `@import '~assets/someClasses' or globally, as I mentioned above


Global import not work, meanwhile simple importing works in dev and causing an error during the building time

Just right after the message: `additional chunk assets processing (91%)`

**Comment by manniL** [comment]
Try `@/assets` as prefix.

> I can't provide anything, I just have mixins and styl file with classes, which are I want to reuse by importing in pages via `@import '~assets/someClasses' or globally, as I mentioned above

Then you *can* reproduce it by putting them in a codesandbox so I can play around with the project ;)

**Comment by chiboreache** [comment]
Just loaded my mega neat setup into CS, and apparently `@import` does not provide any errors... Maybe something with my local webpack, but I'll investigate that tomorrow, I'm going to sleep, finally :crescent_moon:

furthermore, I realised some **undocumented** logic

```js
css: ['~assets/onlyForStyling.styl'],

styleResources: {
    stylus: ['~assets/everythingElse.styl'] or even
	stylus: ['~assets/*.styl'] but not without css object
  },

```

So it works, sort of
but not like that `css:  ['~assets/styl.styl', '~assets/mixins.styl'],`
or that `css: ['~assets/*.styl'],`


So yeah, have fun heh

https://codesandbox.io/s/o7rppmxmny?fontsize=14&module=%2Fnuxt.config.js
*index — /assets — config*

**Comment by chiboreache** [comment]
So, I'm back
Here is [working example](https://codesandbox.io/s/o7rppmxmny?fontsize=14&module=%2Fassets%2Fpages.styl) *(vuex store stop working for some reason, but whatever)*

My conclusion:

`css:` 
 * handles only with styles in the `.styl` files 
 * doesn't accept wildcard way of importing

`styleResources:`
 * handles only with mixins 
 * accepts wildcard
 * but "getting" only mixin functions from it


---

but I am still get an error for my project 😔

**Comment by vinceumo** [comment]
Hi, I have a similar issue

I'm currently upgrading my project from:

```bash
"nuxt": 2.3.4
"nuxt-sass-resources-loader": 2.0.5
````

to:

```bash
"nuxt": 2.6.1
"@nuxtjs/style-resources": "^0.1.2"
```

When I try to build I get the folling error

```bash
 ERROR  Failed to compile with 1 errors                     friendly-errors 10:28:45

This relative module was not found:                         friendly-errors 10:28:45
                                                            friendly-errors 10:28:45
* ./MainFooter.vue?vue&type=style&index=0&id=5d82224f&lang=scss&scoped=true& in ./components/MainFooter.vue
```

If I remove all the styles in my components then I get no error :/

I did change my `nuxt.config.js` with

```js
module.exports = {
  css: ["@/assets/styles/global.scss"],
  modules: ["@nuxtjs/pwa", "@nuxtjs/markdownit", "@nuxtjs/style-resources"],
  styleResources: {
    scss: [
      "./assets/styles/vendors/_family.scss",
      "./assets/styles/functions/**/*.scss",
      "./assets/styles/mixins/**/*.scss",
      "./assets/styles/variables/**/*.scss"
    ]
  },
}
```

I tried to change `./` to `@/` or `~` but lo luck.

The error can be found in the following branch https://github.com/vinceumo/vincent-humeau.com/tree/Nuxt-upgrade

Thanks
