### ISSUE TITLE
"Module should export a function" while building a project

### ISSUE THREAD

**Issue by OndrejCibulka** [nuxt-community/style-resources-module#84]
Hello everyone!

I am trying to build my Nuxt.js project with `@nuxtjs/style-resources` installed.
Yesterday everything worked perfectly, but today i am getting this error:

```
FATAL  Module should export a function: @nuxtjs/style-resources                                                                                                                                                                                           09:53:55

  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:168:13)
  at promise.then (node_modules\@nuxt\utils\dist\utils.js:1796:43)

Error: Module should export a function: @nuxtjs/style-resources
    at ModuleContainer.addModule (D:\My Stuff\foto-denik\node_modules\@nuxt\core\dist\core.js:168:13)
    at promise.then (D:\My Stuff\foto-denik\node_modules\@nuxt\utils\dist\utils.js:1796:43)

```
This is my config:

```
modules: [
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    '@nuxtjs/auth',
    '@nuxtjs/style-resources',
],

styleResources: {
    scss: [
        '~/assets/scss/_variables.scss'
    ]
},
```

Does anyone have an idea what could cause this error?

Thank you for every answer!

**Comment by OrestHk** [comment]
Hello,

`@nuxtjs/style-resources` should be part of the `buildModules` property of your config (see [here](https://github.com/nuxt-community/style-resources-module#setup))
```
buildModules; [
    '@nuxtjs/style-resources'
],
modules: [
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    '@nuxtjs/auth'
],
styleResources: {
    scss: [
        '~/assets/scss/_variables.scss'
    ]
},
```

Hope it helps !

**Comment by rchl** [comment]
Hopefully this is solved.
That said, it's recommended but not necessary to have it in `buildModules`.
