### ISSUE TITLE
Fatal Error after upgrading to nuxt 2.10.2

### ISSUE THREAD

**Issue by rwam** [nuxt-community/style-resources-module#89]
After upgrading from nuxt 2.10.1 to 2.10.2 our build fails with the following error:

```bash
ERROR in ./node_modules/vuetify/src/components/VBadge/VBadge.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./node_modules/vuetify/src/components/VBadge/VBadge.sass)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

    at validateOptions (/…/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.loader (/…/node_modules/css-loader/dist/index.js:44:28)
```

After hours of investigation I found out that removing this module let work the build again. But removing this module also means removing global sass variables and mixins etc. So could not be a  solution. 

The error comes from css-loader and maybe it depends on a [breaking change of handling loader-options](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#300-2019-06-11)

I compared the versions of css-loader and it seems that this could be the cause:

`yarn why css-loader` with 2.10.1:
```bash
$ yarn why css-loader
yarn why v1.19.1
[1/4] 🤔  Why do we have the module "css-loader"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "css-loader@2.1.1"
info Reasons this module exists
   - "vuepress#@vuepress#core" depends on it
   - Hoisted from "vuepress#@vuepress#core#css-loader"
info Disk size without dependencies: "328KB"
info Disk size with unique dependencies: "2.43MB"
info Disk size with transitive dependencies: "6.63MB"
info Number of shared dependencies: 32
=> Found "@storybook/core#css-loader@3.3.2"
info This module exists because "@storybook#vue#@storybook#core" depends on it.
info Disk size without dependencies: "144KB"
info Disk size with unique dependencies: "2.29MB"
info Disk size with transitive dependencies: "6.45MB"
info Number of shared dependencies: 32
=> Found "@nuxt/webpack#css-loader@3.2.0"
info This module exists because "nuxt#@nuxt#webpack" depends on it.
✨  Done in 1.23s.
```
and after upgrading to 2.10.2
```bash
$ yarn why css-loader
yarn why v1.19.1
[1/4] 🤔  Why do we have the module "css-loader"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "css-loader@3.3.2"
info Has been hoisted to "css-loader"
info Reasons this module exists
   - Hoisted from "@storybook#vue#@storybook#core#css-loader"
   - Hoisted from "nuxt#@nuxt#webpack#css-loader"
info Disk size without dependencies: "124KB"
info Disk size with unique dependencies: "2.21MB"
info Disk size with transitive dependencies: "6.37MB"
info Number of shared dependencies: 32
=> Found "@vuepress/core#css-loader@2.1.1"
info This module exists because "vuepress#@vuepress#core" depends on it.
✨  Done in 1.00s.
```
I'm at a loss and need some tips.

**Comment by rwam** [comment]
The solution depends on a version mismatch of core-js. Nuxt uses per default version 2 and Storybook version 3. So to solve the issue I have to follow this note from [@nuxt/babel-preset-app](https://github.com/nuxt/nuxt.js/blob/4ca253e0b82980daa6912070ec54127d12acd169/packages/babel-preset-app/README.md):

> **Note:** Since core-js@2 and core-js@3 are both supported from Babel 7.4.0, we recommend directly adding core-js and setting the version via the corejs option.

I get a working environment again with Nuxt 2.11.0 using [this update](https://github.com/nuxt/nuxt.js/blob/4ca253e0b82980daa6912070ec54127d12acd169/packages/babel-preset-app/README.md#example-2-use-core-js3) on my **nuxt.config.js**:

```bash
yarn add --dev core-js@3 @babel/runtime-corejs3
```
```javascript
export default {
  …
  build: {
    babel: {
      presets() {
        return [
          [
            '@nuxt/babel-preset-app',
            {
              corejs: { version: 3 }
            }
          ]
        ]
      }
    }
  }
}
```
